### ISSUE TITLE
Release SpaDES.core 2.0.2

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/SpaDES.core#225]
Ensure dependency availability or CRAN:

* [x] `Require`
* [x] `reproducible`
* [x] `SpaDES.tools`

Fixes for some outstanding issues:

* [ ] PredictiveEcology/SpaDES.core#194 
* [x] PredictiveEcology/SpaDES.core#210 
* [x] PredictiveEcology/SpaDES.core#219 
* [x] PredictiveEcology/SpaDES.core#224 
* [x] PredictiveEcology/SpaDES.core#227 
* [x] PredictiveEcology/SpaDES.core#229 
* [x] PredictiveEcology/SpaDES.core#236 
      (issue using `reproducible@development`, not CRAN version)
* [ ] PredictiveEcology/SpaDES.core#237 
      (issue using `reproducible@development`, not CRAN version)
* [x] PredictiveEcology/SpaDES.core#238 (resolved for now; revisit)

Prepare for release:

* [x] `git pull`
* [x] Check [current CRAN check results](https://cran.rstudio.org/web/checks/check_results_SpaDES.core.html)
* [x] [Polish NEWS](https://style.tidyverse.org/news.html#news-release)
* [x] `spelling::spell_check_package()`
* [x] `spelling::update_wordlist()`
* [x] `urlchecker::url_check()`
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [x] `rhub::check_for_cran()`
* [x] `revdepcheck::revdep_check(num_workers = 4)`
* [x] Update `cran-comments.md`
* [x] `git push`

Submit to CRAN:

* [x] `usethis::use_version('major')`
* [x] `devtools::submit_cran()`
* [x] Approve email

Wait for CRAN...

* [x] Accepted :tada:
* [x] `git push`
* [x] `usethis::use_github_release()`
* [x] `usethis::use_dev_version()`
* [x] `git push`

**Comment by eliotmcintire** [comment]
I think the window for submitting this version passed a few months ago. I don't think we can get this to pass without submitting the next `Require` and `reproducible` prior` to this version.

**Comment by achubaty** [comment]
v2.02 now on CRAN
